name: GlitchServerPlugin
version: '1.0-SNAPSHOT'
main: net.daylight.test.Main
api-version: '1.21'

commands:
  evilTotem:
    description: Gives totem
    usage: /eviltotem
    permission: glitch.evilTotem
  rtpItem:
    description: Gives rtpItem
    usage: /rtpItem
    permission: glitch.rtpItem

permissions:
  glitch.evilTotems:
    default: op
